_BASE_: "../../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "pretrained_backbones/swin_tiny_patch4_window7_224_converted.pth"
  RESNETS:
    DEPTH: 50
  BACKBONE:
    NAME: "build_retinanet_swint_fpn_backbone"
    FREEZE_AT: -1 #NOTE: swinT specifc
  SWINT:
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
    TOP_LEVELS: 2 #NOTE: swinT specifc
  DISTILLATOR:
    TEACHER:
        META_ARCH: 'DynamicTeacher'
        SOLVER:
            OPTIMIZER: 'ADAMW'
            BASE_LR: 1e-4
            WEIGHT_DECAY: 0.05
            MOMENTUM: 0.9
            LR_SCHEDULER_NAME: "WarmupMultiStepLR"
            STEPS: (210000, 250000)
            GAMMA: 0.1
            WARMUP_FACTOR: 1e-3
            WARMUP_ITERS:  1e03
            WARMUP_METHOD: "linear"
        INTERACT_PATTERN: 'stuGuided'
        DETACH_APPEARANCE_EMBED: False
        ADD_CONTEXT_BOX: True
    STUDENT:
        META_ARCH: 'RetinaNetCT'
        SOLVER:
            OPTIMIZER: 'ADAMW'
            BASE_LR: 1e-4
            WEIGHT_DECAY: 0.05
            MOMENTUM: 0.9
            LR_SCHEDULER_NAME: "WarmupMultiStepLR"
            STEPS: (210000, 250000)
            GAMMA: 0.1
            WARMUP_FACTOR: 1e-3
            WARMUP_ITERS:  1e03
            WARMUP_METHOD: "linear"
    ADAPTER:
        META_ARCH: 'SequentialConvs'
    PRE_NONDISTILL_ITERS: 30000
    PRE_FREEZE_STUDENT_BACKBONE_ITERS: 20000
    LAMBDA: 1.0
    EVAL_TEACHER: True

SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "outputs/RetinaNet/retinanet_Swin_Tiny_3xMS_stuGuided_addCtxBox=YES_detachAppearanceEmbed=NO_preNondistillIters=30k_preFreezeStudentBackboneIters=20k"
