_BASE_: "../../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  DISTILLATOR:
    TEACHER:
        META_ARCH: 'DynamicTeacher'
        SOLVER:
            OPTIMIZER: 'SGD'
            BASE_LR: 0.01
            MOMENTUM: 0.9
            WEIGHT_DECAY: 1e-4
            LR_SCHEDULER_NAME: "WarmupMultiStepLR"
            STEPS: (60000, 80000)
            GAMMA: 0.1
            WARMUP_FACTOR: 1e-3
            WARMUP_ITERS:  1e03
            WARMUP_METHOD: "linear"
        INTERACT_PATTERN: 'stuGuided'
        DETACH_APPEARANCE_EMBED: True
        ADD_CONTEXT_BOX: True
    STUDENT:
        META_ARCH: 'RetinaNetCT'
        SOLVER:
            OPTIMIZER: 'SGD'
            BASE_LR: 0.01
            MOMENTUM: 0.9
            WEIGHT_DECAY: 1e-4
            LR_SCHEDULER_NAME: "WarmupMultiStepLR"
            STEPS: (60000, 80000)
            GAMMA: 0.1
            WARMUP_FACTOR: 1e-3
            WARMUP_ITERS:  1e03
            WARMUP_METHOD: "linear"
    ADAPTER:
        META_ARCH: 'SequentialConvs'
    PRE_NONDISTILL_ITERS: 20000
    PRE_FREEZE_STUDENT_BACKBONE_ITERS: 10000
    LAMBDA: 1.0
    EVAL_TEACHER: True
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
OUTPUT_DIR: 'outputs/RetinaNet/retinanet_R_50_1xMS_stuGuided_addCtxBox=YES_detachAppearanceEmbed=YES_preNondistillIters=20k/'
