_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "pretrained_backbones/swin_tiny_patch4_window7_224_converted.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  BACKBONE:
    NAME: "build_swint_fpn_backbone"
    FREEZE_AT: -1 #NOTE: swinT specifc
  SWINT:
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"] #NOTE: swinT specifc
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"] #NOTE: swinT specifc
    TOP_LEVELS: 2 #NOTE: swinT specifc
  DISTILLATOR:
    LABEL_ENCODER:
        LOAD_LABELMAP: True
    TEACHER:
        META_ARCH: 'DynamicTeacher'
        SOLVER:
            OPTIMIZER: 'SGD'
            BASE_LR: 0.02
            MOMENTUM: 0.9
            WEIGHT_DECAY: 1e-4
            LR_SCHEDULER_NAME: "WarmupMultiStepLR"
            STEPS: (210000, 250000)
            GAMMA: 0.1
            WARMUP_FACTOR: 1e-3
            WARMUP_ITERS:  1e03
            WARMUP_METHOD: "linear"
        INTERACT_PATTERN: 'stuGuided'
        DETACH_APPEARANCE_EMBED: True
        ADD_CONTEXT_BOX: False
    STUDENT:
        META_ARCH: 'RCNNCT'
        SOLVER:
            OPTIMIZER: 'ADAMW'
            BASE_LR: 1e-4
            MOMENTUM: 0.9
            WEIGHT_DECAY: 0.05
            LR_SCHEDULER_NAME: "WarmupMultiStepLR"
            STEPS: (210000, 250000)
            GAMMA: 0.1
            WARMUP_FACTOR: 1e-3
            WARMUP_ITERS:  1e03
            WARMUP_METHOD: "linear"
    ADAPTER:
        META_ARCH: 'SequentialConvs'
    PRE_NONDISTILL_ITERS: 30000
    PRE_FREEZE_STUDENT_BACKBONE_ITERS: 20000
    LAMBDA: 1.0
    EVAL_TEACHER: True
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: 'outputs/MaskRCNN/mask_rcnn_Swin_Tiny_3xMS_stuGuided_addCtxBox=NO_detachAppearanceEmbed=YES_preNondistillIters=30k_preFreezeStudentBackboneIters=20k_2nd'
